export const propertyAgencyParsePayloadEnToPt = <T>(source: any) => ({
  client_id: source.client_id,
  owner: source.owner,
  ownerPhone: source.owner_phone,
  ownerEmail: source.owner_email,
  state: source.state,
  city: source.city,
  address: source.address,
  neighborhood: source.neighborhood,
  tipo: source.type,
  dormitorio: source.bedrooms,
  garagem: source.garage,
  lavanderia: source.laundry,
  alarme: source.alarm,
  portaoEletronico: source.electronic_gate,
  elevador: source.elevator,
  pocoArtesiano: source.artesian_well,
  cercaEletrica: source.electric_fence,
  cameraDeVideo: source.video_camera,
}) as T

export const propertyAgencyParsePayloadPtToEn = <T>(source: any) => ({
  client_id: source.client_id,
  owner: source.owner,
  owner_phone: source.ownerPhone,
  owner_email: source.ownerEmail,
  state: source.state,
  city: source.city,
  address: source.address,
  neighborhood: source.neighborhood,
  type: source.tipo,
  bedrooms: source.dormitorio,
  garage: source.garagem,
  laundry: source.lavanderia,
  alarm: source.alarme,
  electronic_gate: source.portaoEletronico,
  elevator: source.elevador,
  artesian_well: source.pocoArtesiano,
  electric_fence: source.cercaEletrica,
  video_camera: source.cameraDeVideo,
}) as T
